# Generated by Django 4.2.1 on 2023-06-04 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_produto/')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de criacão')),
                ('alteracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de alteração')),
                ('imagens', models.ManyToManyField(blank=True, to='produto.imagemproduto')),
            ],
        ),
    ]
