# Generated by Django 4.2.1 on 2023-06-04 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_descricao_produto_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagens',
        ),
    ]
