# Generated by Django 4.2.1 on 2023-06-05 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_remove_produto_imagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemproduto',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='produto.produto'),
        ),
    ]
