# Generated by Django 4.2.2 on 2023-06-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_imagemproduto_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemproduto',
            name='imagem',
            field=models.ImageField(upload_to='produto/static/imagens_produto/'),
        ),
    ]
