# Generated by Django 4.2.2 on 2023-06-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrinho",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
