# Generated by Django 4.2.2 on 2023-06-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0002_alter_carrinho_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcarrinho",
            name="observacao",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="itemcarrinho",
            name="quantidade",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="itempedido",
            name="observacao",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="itempedido",
            name="quantidade",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(default="Pendente", max_length=50),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
