# Generated by Django 4.2.2 on 2023-06-15 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0003_alter_itemcarrinho_observacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcarrinho",
            name="carrinho",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="pedido.carrinho",
            ),
        ),
    ]
