# Generated by Django 4.2.2 on 2023-06-15 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0004_alter_itemcarrinho_carrinho"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itempedido",
            name="pedido",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="pedido.pedido",
            ),
        ),
    ]
