# Generated by Django 4.2.2 on 2023-06-15 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0004_imagemproduto_produto"),
        ("pedido", "0006_itemcarrinho_valor"),
    ]

    operations = [
        migrations.RemoveField(model_name="itemcarrinho", name="produto",),
        migrations.AddField(
            model_name="itemcarrinho",
            name="produto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="produto.produto",
            ),
        ),
    ]
