# Generated by Django 4.2.1 on 2023-06-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0008_alter_itemcarrinho_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='observacao',
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(null=True),
        ),
    ]
