# Generated by Django 4.2.1 on 2023-06-16 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_remove_itempedido_observacao_pedido_observacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='observacao',
        ),
    ]
