# Generated by Django 4.2.2 on 2023-06-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0012_itemcarrinho_total_itempedido_total_itempedido_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
