# Generated by Django 4.2.2 on 2023-06-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0013_alter_pedido_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PREPARO', 'Em Preparo'), ('CONCLUIDO', 'Concluido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=50),
        ),
    ]
